### ISSUE TITLE
FR: Attributes Enhancement 

### ISSUE THREAD

**Issue by omidp** [javaee5/PersianScheduler#2]
I wondered if we could add more attributes including defaultDate, editable,... instead of one attribute as value.

WDYT ?

**Comment by hamed-hatami** [comment]
Yes, it could have more attribute instead of value but I was in a hurry to build two days ago and now we can extend it to more attribute

**Comment by hamed-hatami** [comment]
Dear Omid,

Attributes add to the component and commit to gothub

Regards,
Hamed Hatami

**Comment by omidp** [comment]
Great, I will test it and let you know the results if anything goes wrong. for now I'll just close this issue.
